name: linting and Automated Versioning

on:
  pull_request:

jobs:
  
  linting:
     name: Run linters
     runs-on: ubuntu-latest
     steps:
       - name: Check out Git repository
         uses: actions/checkout@v4

       - name: Set up Node.js
         uses: actions/setup-node@v1
         with:
           node-version: 20

       # ESLint and Prettier must be in `package.json`
       - name: Install Node.js dependencies
         run: npm ci

       - name: Fix lint issues
         run: npx eslint '**.js' --fix

       - name: Verification (cat index.js)
         run: cat index.js

  
  