name: Lint and Format
on: [push, pull_request]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: git clone https://github.com/khadija-AC/husky-project.git

      - name: Set up Node.js
        uses: npm install node
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      